language: node_js

node_js:
- "8"

cache:
  directories:
  - node_modules

env:
  global:
    - secure: "" # Add ecrypted vars here

before_install:
- npm install @alrra/travis-scripts@3.0.1
- |

  $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXX_key" \
                        --iv "$encrypted_XXXXXXXXXX_iv" \
                        --path-encrypted-key "./api-keys/travis.enc"
install:
  - npm ci

script:
  - return 0 # Add your tests, build, etc here

after_success:
  - npm run safe-sync